ulimit -n 2048

#load nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

export PATH="$(brew --prefix qt@5.5)/bin:$PATH"
export PATH=/opt/local/bin:/opt/local/sbin:$PATH

export PATH="$HOME/.crenv/bin:$PATH"
eval "$(crenv init -)"

alias code="/usr/local/bin/code"
